#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\buildscripts\build.ps1

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
